---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-22
    image: ubuntu:22.04
    privileged: true
    command: /sbin/init
  - name: debian-12
    image: debian:12
    privileged: true
    command: /sbin/init
  - name: rocky-9
    image: rockylinux:9
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint: |
    ansible-lint
verifier:
  name: ansible
